### ISSUE TITLE
Remove notification CPT from search query

### ISSUE THREAD

**Issue by EneMarine** [Ninadjeret/wp-plugins-notifications-center#9]

**Comment by Ninadjeret** [comment]
It will be changed on next release. Until, you can fix it using `voy/notif/install/register_cpt` filter

**Comment by Ninadjeret** [comment]
`add_filter('voy/notif/install/register_cpt', 'exclude_notifications_from_search');
        
function exclude_notifications_from_search( $args ) {
    $args['exclude_from_search'] = true;
    return $args;
}`
